Revert "[RoPE] Cleanup RoPE implementation (#1514)" (#1533)
This reverts commit 6f3f3504d5e4a3e1c259d899316979e867516c4f.

We were seeing an issue in the Shortfin server, while running mistral
and tracked it down to a regression in accuracy. Bisecting led to this
commit as being the culprit.

Initially, this presented itself as a numpy NaN error in the server:

```bash
/shark-ai/shortfin/src/shortfin/support/iree_helpers.h:315: UNKNOWN; Unhandled exception: Traceback (most recent call last):
  File "numpy/random/mtrand.pyx", line 990, in numpy.random.mtrand.RandomState.choice
RuntimeError: Async exception on <Worker 'default-fiber-pool-init-worker-0'>): probabilities contain NaN
```

Was able to track this down to being caused by NaNs in the logits,
directly after decode invocation. Those NaNs eventually get passed to
the `Sampler.sample_top_p` function.

When error wasn't thrown, this issue would also present itself with
inaccurate or empty output:

```bash
curl http://localhost:8001/generate -H "Content-Type: application/json" -d '{ "return_text_in_logprobs": "False", "stream": "False", "text":  "life is amazing, is it not? ", "sampling_params": {"max_completion_tokens": 64, "b_of_n":1}}'
{"responses": [{"prompt": "life is amazing, is it not? ", "responses": [{"text": ""}, {"text": ""}, {"text": ""}, {"text": ""}, {"text": ""}, {"text": ""}, {"text": ""}, {"text": ""}]}]}%
```

After bisecting, was able to rule out IREE side, by re-compiling a
golden MLIR that still worked. Bisecting through sharktank side showed
this commit to be the issue. **Reverting fixes the accuracy issues and
the numpy NaN issue**.

Still need to track down why this was able to slip through our CIs. This
may be something specific to Mistral, as PPL tests, Llama based smoke
tests, etc. don't show an error.