Fail out early if mismatch in tensor_parallelism_size (#1361)
Currently if you have a mismatch between `--tensor-parallelism-size` and
the sharding of the provided IRPA file you will get a hard to understand
error message.
E.g. if you provide an unsharded IRPA, but specified to
`export_paged_llm_v1` that the data is sharded with TP>1 you will get
the following hard to understand error.
```
  File "/home/alvasile/repos/shark-ai/sharktank/sharktank/ops/signatures.py", line 292, in _embedding_lookup_trampoline
    d.fail(tensors)
  File "/home/alvasile/repos/shark-ai/sharktank/sharktank/ops/_registry.py", line 270, in fail
    raise NotImplementedError(
NotImplementedError: Overridable operator sharktank.ops.signatures.embedding_lookup does not have an implementation for argument types: [<class 'sharktank.types.tensors.ReplicatedTensor'>, <class 'sharktank.types.tensors.DefaultPrimitiveTensor'>]
```

Signed-off-by: Alex Vasile <48962821+Alex-Vasile@users.noreply.github.com>