Remove hardcoded split for top-k=1 (#1822)
Remove hardcoded split for top-k=1. If `--top-k=1` is specified in the
export, the dim size will not be a multiple of the chunk size: [command
and full stack
trace](https://gist.github.com/AmosLewis/ab3d8a5defe96ed79ee570dd22f486d2#file-llama_405b_fp4_pp1_export_bug-md)
```
ValueError: dim's size must be a multiple of chunk_size.
Dim Size: 2
Chunk Size: 1024
```
From my understanding, the compiler will do the split, so we do not need
to manually split it in the sharktank export.

Signed-off-by: aviator19941 <avinash.sharma@amd.com>